
-- ==========================================
-- DROP TABLES (Ordenadas por dependencia inversa)
-- ==========================================

-- Tablas dependientes de nivel más profundo (Tablas relacionales / estadísticas / récords)
DROP TABLE BASKET.CAMPEONATO CASCADE CONSTRAINTS;
DROP TABLE BASKET.ESTADISTICA_HISTORICA CASCADE CONSTRAINTS;
DROP TABLE BASKET.RECORD_JUGADOR CASCADE CONSTRAINTS;
DROP TABLE BASKET.CUOTA_APUESTA CASCADE CONSTRAINTS;
DROP TABLE BASKET.JUGADOR_EQUIPO CASCADE CONSTRAINTS;
DROP TABLE BASKET.RECORD_EQUIPO CASCADE CONSTRAINTS;

-- Tablas intermedias (Dependen de Países, Ligas, Equipos, etc.)
DROP TABLE BASKET.CASA_APUESTA CASCADE CONSTRAINTS;
DROP TABLE BASKET.EQUIPO CASCADE CONSTRAINTS;
DROP TABLE BASKET.LIGA CASCADE CONSTRAINTS;
DROP TABLE BASKET.JUGADOR CASCADE CONSTRAINTS;
DROP TABLE BASKET.TOKEN_USUARIO CASCADE CONSTRAINTS;
DROP TABLE BASKET.USUARIO CASCADE CONSTRAINTS;

-- Tablas base / independientes (Referenciadas por otras)
DROP TABLE BASKET.PAIS CASCADE CONSTRAINTS;
DROP TABLE BASKET.MOTIVO_ESTADO CASCADE CONSTRAINTS;

DROP USER BASKET;