
-- TODO: INSERTS QUE DEBO CREAR.
	-- CRER UN MOTIVO ESTADO QUE EXPLIQUE CUANDO -- EL REFRESH TOKEN ESTA VENCIDO
CREATE TABLE BASKET.MOTIVO_ESTADO(
	motivo_estado_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nombre NVARCHAR2(50) NOT NULL,
	descripcion NVARCHAR2(500) NOT NULL,
	estado CHAR(2) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	CONSTRAINT chk_motivo_estado 
		CHECK (estado IN ('AC', 'IN'))
);


CREATE TABLE BASKET.USUARIO(
	usuario_id NUMBER GENERATED	ALWAYS AS IDENTITY PRIMARY KEY,
	nombre NVARCHAR2(50) NOT NULL,
	apellido NVARCHAR2(100) NOT NULL,
	correo NVARCHAR2(100) NOT NULL,
	contrasenia NVARCHAR2(100) NOT NULL,
	estado CHAR(2) NOT NULL,
	motivo_estado_id NUMBER	NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT chk_usuario
		CHECK (estado IN ('AC', 'IN')),
	CONSTRAINT fk_usuario_motivo_estado_id FOREIGN KEY (motivo_estado_id)
		REFERENCES BASKET.MOTIVO_ESTADO(motivo_estado_id),
	CONSTRAINT uk_usuario_correo UNIQUE	(correo)
);

CREATE TABLE BASKET.TOKEN_USUARIO(
	token_usuario_id NUMBER	GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	usuario_id NUMBER NOT NULL,
	refreshToken NVARCHAR2(500) NOT NULL,
	motivo_estado_id NUMBER	NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	fecha_vencimiento TIMESTAMP NOT NULL,
	estado CHAR(2) NOT NULL,
	CONSTRAINT fk_token_usuario_usuario_id FOREIGN KEY (usuario_id)
		REFERENCES BASKET.USUARIO(usuario_id),
	CONSTRAINT chk_token_usuario
		CHECK (estado IN ('AC', 'IN', 'VE')),
	CONSTRAINT fk_token_usuario_motivo_estado_id FOREIGN KEY (motivo_estado_id)
		REFERENCES BASKET.MOTIVO_ESTADO(motivo_estado_id)
);

-- BUSCAR ESA INFO CON IA Y HACER UN INSERTS, PARA CONSTRUIR UN ENDPOINT
CREATE TABLE BASKET.PAIS (
    pais_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ISO2 CHAR(2) NOT NULL,
    codigo_ISO3 CHAR(3) NOT NULL,
    nombre NVARCHAR2(100) NOT NULL,
    nombre_oficial NVARCHAR2(200) NULL,
    capital NVARCHAR2(100) NULL,
    latitud NUMBER(9,6) NULL,
    longitud NUMBER(9,6) NULL,
    continente NVARCHAR2(50) NULL,
    estado CHAR(2) NOT NULL,
    CONSTRAINT UK_PAIS_ISO2 UNIQUE (codigo_ISO2),
    CONSTRAINT UK_PAIS_ISO3 UNIQUE (codigo_ISO3),
    CONSTRAINT CK_PAIS_ACTIVO 
    	CHECK (estado IN ('AC', 'IN')),
    CONSTRAINT CK_PAIS_LATITUD 
    	CHECK (latitud BETWEEN -90 AND 90),
    CONSTRAINT CK_PAIS_LONGITUD 
    	CHECK (longitud BETWEEN -180 AND 180)
);

CREATE TABLE BASKET.LIGA(
	liga_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nombre NVARCHAR2(50) NOT NULL,
	descripcion NVARCHAR2(100) NOT NULL,
	pais_id NUMBER NOT NULL,
	estado CHAR(2) NOT NULL,
	motivo_estado_id NUMBER	NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT fk_liga_pais_id FOREIGN KEY (pais_id)
		REFERENCES BASKET.PAIS(pais_id),
	CONSTRAINT chk_liga_estado
		CHECK (estado IN ('AC', 'IN')),
	CONSTRAINT fk_liga_motivo_estado_id FOREIGN KEY (motivo_estado_id)
		REFERENCES BASKET.MOTIVO_ESTADO(motivo_estado_id)
);

CREATE TABLE BASKET.EQUIPO(
	equipo_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	liga_id NUMBER NOT NULL,
	nombre NVARCHAR2(100) NOT NULL,
	anio_fundacion DATE NOT NULL,
	estado CHAR(2) NOT NULL,
	motivo_estado_id NUMBER	NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT chk_equipo_estado
		CHECK (estado IN ('AC', 'IN')),
	CONSTRAINT fk_equipo_motivo_estado_id FOREIGN KEY (motivo_estado_id)
		REFERENCES BASKET.MOTIVO_ESTADO(motivo_estado_id)
);

CREATE TABLE BASKET.CASA_APUESTA(
	casa_apuesta_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY	KEY,
	nombre NVARCHAR2(50) NOT NULL,
	url_sitio NVARCHAR2(100) NULL,
	estado CHAR(2) NOT NULL,
	motivo_estado_id NUMBER	NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT chk_casa_apuesta
		CHECK (estado IN ('AC', 'IN')),
	CONSTRAINT fk_casa_apuesta_motivo_estado_id FOREIGN KEY (motivo_estado_id)
		REFERENCES BASKET.MOTIVO_ESTADO(motivo_estado_id)
);

CREATE TABLE BASKET.RECORD_EQUIPO(
	record_equipo_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	equipo_id NUMBER NOT NULL,
	tipo_record NVARCHAR2(100) NOT NULL,
	valor_record NVARCHAR2(100) NOT NULL,
	fecha_logro DATE NOT NULL,
	estado CHAR(2) NOT NULL,
	motivo_estado_id NUMBER	NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT fk_record_equipo_equipo_id FOREIGN KEY (equipo_id)
		REFERENCES BASKET.EQUIPO(equipo_id),
	CONSTRAINT chk_record_equipo
		CHECK (estado IN ('AC', 'IN')),
	CONSTRAINT fk_record_equipo_motivo_estado_id FOREIGN KEY (motivo_estado_id)
		REFERENCES BASKET.MOTIVO_ESTADO(motivo_estado_id)
);

CREATE TABLE BASKET.JUGADOR(
	jugador_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	nombre NVARCHAR2(50) NOT NULL,
	apellido NVARCHAR2(100) NOT NULL,
	fecha_nacimiento DATE  NOT NULL,
	posicion NVARCHAR2(50) NOT NULL,
	altura number(9,6) NOT NULL,
	peso number(9,6) NOT NULL,
	url_imagen NVARCHAR2(100) NULL, --> AQUI SE DEBE COLOCAR LA URL DE AZURE EN DONDE DESPLEGARE LAS IMAGENES DE LOS JUGADORES.
	estado CHAR(2) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT chk_jugador
		CHECK (estado IN ('AC', 'IN'))
);

CREATE TABLE BASKET.JUGADOR_EQUIPO(
	jugador_equipo_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	jugador_id NUMBER NOT NULL,
	equipo_id NUMBER NOT NULL,
	temporada VARCHAR2(50) NOT NULL,
	fecha_ingreso DATE NOT NULL,
	fecha_salida DATE NULL,
	estado CHAR(2) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT fk_jugador_equipo_jugador_id FOREIGN KEY(jugador_id)
		REFERENCES BASKET.JUGADOR(jugador_id),
	CONSTRAINT fk_jugador_equipo_equipo_id FOREIGN KEY(equipo_id)
		REFERENCES BASKET.EQUIPO(equipo_id),
	CONSTRAINT chk_jugador_equipo
		CHECK (estado IN ('AC', 'IN'))
);

CREATE TABLE BASKET.CUOTA_APUESTA(
	cuota_apuesta_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	casa_apuesta_id NUMBER NOT NULL,
	descripcion_evento NVARCHAR2(500) NULL,
	tipo_mercado VARCHAR2(50) NULL,
	valor_cuota NUMBER(12, 5) NULL,
	estado CHAR(2) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT fk_cuota_apuesta_casa_apuesta_id FOREIGN KEY(casa_apuesta_id)
		REFERENCES BASKET.CASA_APUESTA(casa_apuesta_id),
	CONSTRAINT chk_cuota_apuesta
		CHECK (estado IN ('AC', 'IN'))
);

CREATE TABLE BASKET.RECORD_JUGADOR(
	record_jugador_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	jugador_id NUMBER NOT NULL,
	tipo_record NVARCHAR2(100) NOT NULL,
	valor_record NVARCHAR2(100) NOT NULL,
	fecha_logro DATE NOT NULL,
	estado CHAR(2) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT fk_record_jugador_jugador_id FOREIGN KEY(jugador_id)
		REFERENCES BASKET.JUGADOR(jugador_id),
	CONSTRAINT chk_record_jugador
		CHECK (estado IN ('AC', 'IN'))
);

CREATE TABLE BASKET.ESTADISTICA_HISTORICA(
	estadistica_historica_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	jugador_id NUMBER NOT NULL,
	equipo_id NUMBER NOT NULL,
	temporada VARCHAR2(50) NOT NULL,
	partidos_jugados NUMBER NOT NULL,
	puntos_por_partidos NUMBER NOT NULL,
	asistencias_por_partido NUMBER(12, 5) NULL,
	estado CHAR(2) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT fk_estadistica_historica_jugador_id FOREIGN KEY(jugador_id)
		REFERENCES  BASKET.JUGADOR(jugador_id),
	CONSTRAINT fk_estadistica_historica_equipo_id FOREIGN KEY(equipo_id)
		REFERENCES BASKET.EQUIPO(equipo_id),
	CONSTRAINT chk_estadistica_historica
		CHECK (estado IN ('AC', 'IN'))
);

CREATE TABLE BASKET.CAMPEONATO(
	campeonato_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	jugador_id NUMBER NOT NULL,
	equipo_id NUMBER NOT NULL,
	nombre_titulo NVARCHAR2(50) NOT NULL,
	temporada VARCHAR2(50) NOT NULL,
	estado CHAR(2) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_ultima_actualizacion TIMESTAMP NULL,
	CONSTRAINT fk_campeonato_jugador_id FOREIGN KEY(jugador_id)
		REFERENCES  BASKET.JUGADOR(jugador_id),
	CONSTRAINT fk_campeonato_equipo_id FOREIGN KEY(equipo_id)
		REFERENCES BASKET.EQUIPO(equipo_id),
	CONSTRAINT chk_campeonato
		CHECK (estado IN ('AC', 'IN'))
);
